apiVersion: v1
kind: Secret
metadata: 
  name: {{.Values.secret.name}}
data: 
  CONNSTR_AdminConnectionString: {{.Values.secret.data.CONNSTR}}
  CONNSTR_ConnectionString: {{.Values.secret.data.CONNSTR}}
  CONNSTR_DeploymentConfigConnectionString: {{.Values.secret.data.CONNSTR}}

  DBServer: {{.Values.secret.DBServer }}
  DbName: {{.Values.secret.DbName }}
  DbPassword: abc123
  DbUserName: crmnext